services:
  postgres:
    image: postgres:16-alpine
    container_name: uptime-monitor-postgres
    environment:
      POSTGRES_DB: uptime_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/migrations:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    networks:
      - uptime-monitor
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uptime_monitor"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: valkey/valkey:7-alpine
    container_name: uptime-monitor-redis
    command: valkey-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6380}:6379"
    networks:
      - uptime-monitor
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  uptime-monitor-app:
    image: dinhnguyen1812002/webtracker:${IMAGE_TAG:-latest}  # dùng image từ Docker Hub thay vì build local
  
    container_name: uptime-monitor-app
    environment:
      PORT: ${PORT:-8080}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: uptime_monitor
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_SSL_MODE: disable
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      WORKER_POOL_SIZE: ${WORKER_POOL_SIZE:-8}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "${PORT:-8080}:8080"
    networks:
      - uptime-monitor
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  uptime-monitor:
    driver: bridge
